# Build runenv project
# Using tool toml installed with `cargo install toml-cli`

default: lint

properties:
  TARGETS:
    aarch64-unknown-linux-gnu: linux-arm64
    x86_64-unknown-linux-gnu: linux-amd64
    aarch64-apple-darwin: darwin-arm64
    x86_64-apple-darwin: darwin-amd64
    x86_64-pc-windows-gnu: windows-amd64

targets:

  env:
    steps:
    - if: '_OS == "darwin" && _ARCH == "arm64"'
      then:
      - setenv: 'CROSS_CONTAINER_OPTS'
        value:  '--platform linux/amd64'

  lint:
    depends: env
    steps:
    - $: [cargo, check]

  build:
    depends: env
    steps:
    - $: [cargo, build]

  install:
    depends: env
    steps:
    - $: [cargo, install, --path, .]

  binaries:
    depends: env
    steps:
    - mkdir: 'target/runenv'
    - for: target
      in:  =keys(TARGETS)
      do:
      - 'name = TARGETS[target]'
      - print: "Building for target ={name}..."
      - $: [cross, build, --release, --target, =target]
      - copy:  'target/={target}/release/runenv'
        tofile: 'target/runenv/runenv-={name}'
      - copy:  'target/={target}/release/runenv.exe'
        tofile: 'target/runenv/runenv-={name}.exe'

  archive:
    depends: [binaries]
    steps:
    - zip: 'runenv/*'
      dir: 'target'
      tofile: 'target/runenv.zip'

  release:
    depends: [clean, archive]
    steps:
    - $: [toml, get, Cargo.toml, package.version, --raw]
      1=: version
      1x: true
    - $: [git, tag, =version]
    - move: 'target/runenv.zip'
      tofile: 'target/runenv-={version}.zip'
    - copy: install
      todir: 'target/runenv/'
    - $: 'scp target/runenv/* elrond:/web/app/dist/runenv/'
    - $: [git, push, --tags]

  clean:
    steps:
    - $: [cargo, clean]
