default: lint

properties:
  VERSION: '0.1.1'
  TARGETS:
    aarch64-unknown-linux-gnu: linux-arm64
    x86_64-unknown-linux-gnu: linux-amd64
    aarch64-apple-darwin: darwin-arm64
    x86_64-apple-darwin: darwin-amd64
    #x86_64-pc-windows-msvc: windows-amd64

targets:

  env:
    steps:
    - setenv: VERSION
      value:  =VERSION
    - setenv: CROSS_CONTAINER_OPTS
      value:  '--platform linux/amd64'

  lint:
    depends: env
    steps:
    - $: [cargo, check]

  build:
    depends: env
    steps:
    - $: [cargo, build]

  binaries:
    depends: env
    steps:
    - mkdir: 'target/runenv'
    - for: target
      in:  =keys(TARGETS)
      do:
      - 'name = TARGETS[target]'
      - print: "Building for target ={name}..."
      - $: [cross, build, --release, --target, =target]
      - copy:  'target/={target}/release/runenv'
        tofile: 'target/runenv/runenv-={name}'

  archive:
    depends: [binaries]
    steps:
    - zip: 'runenv/*'
      dir: 'target'
      tofile: 'target/runenv.zip'

  release:
    depends: [clean, archive]
    steps:
    - $: [git, tag, =VERSION, -m, 'Release v={VERSION}']
    - move: 'target/runenv.zip'
      tofile: 'target/runenv-={VERSION}.zip'
    - copy: install
      todir: 'target/runenv/'
    - $: 'scp target/runenv/* elrond:/web/app/dist/runenv/'
    - $: [git, push, --tags]

  clean:
    steps:
    - $: [cargo, clean]
